name: steps_app
description: A personal step-by-step task organizer application
version: 1.0.0+1

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI/UX dependencies
  cupertino_icons: ^1.0.2
  
  # State management
  flutter_bloc: ^8.1.3
  
  # Local storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  
  # Utilities
  path: ^1.8.3
  intl: ^0.19.0
  uuid: ^4.1.0
  
  # Common packages from monorepo
  steps_core:
    path: ../../packages/steps_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  # App assets
  assets:
    - assets/images/
    - assets/icons/
  
  # App fonts
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700